# This file was generated by hand for the migration project.
# See https://relishapp.com/rspec/rspec-core/docs/configuration for options.

RSpec.configure do |config|
  config.expect_with :rspec do |expectations|
    expectations.include_chain_clauses_in_custom_matcher_descriptions = true
  end

  config.mock_with :rspec do |mocks|
    mocks.verify_partial_doubles = true
  end

  # Keep top-level `describe`, `context`, `feature`, `scenario` available.
  # If you want stricter RSpec.describe-only style later, uncomment:
  # config.disable_monkey_patching!

  config.filter_run_when_matching :focus
  config.example_status_persistence_file_path = 'spec/examples.txt'

  # Ruby 2.6 + Rails 3.2 produces a lot of deprecation noise; silence it so
  # test output stays readable. Re-enable when you start the Rails upgrades.
  config.warnings = false

  config.order = :random
  Kernel.srand config.seed
end
