class Hymn

  attr_accessor :file,:title

  def initialize(f,t)
    @file = f
    @title = t
  end

  def self.all
    ALL
  end

  
  ALL = [
   Hymn.new("Hymns/Choir-All-Hail-The-Power.mp3","Choir - All Hail The Power"),
   Hymn.new("Hymns/Choir-All-Power-Is-Given.mp3","Choir - All Power Is Given"),
   Hymn.new("Hymns/Choir-All-The-Way-My-Saviour-Leads-Me.mp3","Choir - All The Way My Saviour Leads Me"),
    Hymn.new("Hymns/Choir-Almost-Persuaded.mp3","Choir - Almost Persuaded"),
    Hymn.new("Hymns/Choir-At-Calvary.mp3","Choir - At Calvary"),
    Hymn.new("Hymns/Choir-Banner-Of-The-Cross.mp3","Choir - Banner Of The Cross"),
    Hymn.new("Hymns/Choir-Behold-The-Stranger-At-The-Door.mp3","Choir - Behold The Stranger At The Door"),
    Hymn.new("Hymns/Choir-Blessed-Assurance.mp3","Choir - Blessed Assurance"),
    Hymn.new("Hymns/Choir-Bring-Them-In.mp3","Choir - Bring Them In"),
    Hymn.new("Hymns/Choir-Christ-Arose.mp3","Choir - Christ Arose"),
    Hymn.new("Hymns/Choir-Christ-Is-Risen.mp3","Choir - Christ Is Risen"),
    Hymn.new("Hymns/Choir-Come-My-Soul.mp3","Choir - Come My Soul"),
    Hymn.new("Hymns/Choir-Conquering-Now.mp3","Choir - Conquering Now"),
    Hymn.new("Hymns/Choir-Depth-Of-Mercy.mp3","Choir - Depth Of Mercy"),
    Hymn.new("Hymns/Choir-Fairest-Lord-Jesus.mp3","Choir - Fairest Lord Jesus"),
    Hymn.new("Hymns/Choir-Have-Thine-Own-Way.mp3","Choir - Have Thine On Way"),
    Hymn.new("Hymns/Choir-Head-That-Once-Was-Crowned-With-Thorns.mp3","Choir - Head That Once Was Crowned With Thorns"),
    Hymn.new("Hymns/Choir-He-Careth-For-You.mp3","Choir - He Careth For You"),
    Hymn.new("Hymns/Choir-He-Giveth-More-Grace.mp3","Choir - He Giveth More Grace"),
    Hymn.new("Hymns/Choir-He-Is-Coming-Again.mp3","Choir - He Is Coming Again"),
    Hymn.new("Hymns/Choir-He-Is-So-Precious-To-Me.mp3","Choir - He Is So Precious To Me"),
    Hymn.new("Hymns/Choir-He-Lives-On-High.mp3","Choir - He Lives On High"),
    Hymn.new("Hymns/Choir-He-Will-Hold-Me-Fast.mp3","Choir - He Will Hold Me Fast"),
    Hymn.new("Hymns/Choir-Ho-Reapers.mp3","Choir - Ho Reapers"),
    Hymn.new("Hymns/Choir-How-Can-I-But-Love-Him.mp3","Choir - How Can I But Love Him?"),
    Hymn.new("Hymns/Choir-I-Belong-To-The-King.mp3","Choir - I Belong To The King"),
    Hymn.new("Hymns/Choir-I-Could-Not-Do-Without-Him.mp3","Choir - I Could Not Do Without Him"),
    Hymn.new("Hymns/Choir-I-Heard-The-Voice.mp3","Choir - I Heard The Voice"),
    Hymn.new("Hymns/Choir-I-Know-My-Redeemer-Liveth.mp3","Choir - I Know That My Redeemer Liveth"),
    Hymn.new("Hymns/Choir-I-Know-Of-A-Name.mp3","Choir - I Know Of A Name"),
    Hymn.new("Hymns/Choir-Im-Singing.mp3","Choir - I'm Singing"),
    Hymn.new("Hymns/Choir-I-Need-Thee.mp3","Choir - I Need Thee"),
    Hymn.new("Hymns/Choir-In-The-Sweet-Bye-n-Bye.mp3","Choir - In The Sweet Bye And Bye"),
    Hymn.new("Hymns/Choir-Is-My-Name-Written-There.mp3","Choir - Is My Name Written There ?"),
    Hymn.new("Hymns/Choir-Is-There-Any-Room-For-Jesus.mp3","Choir - Is There Any Room For Jesus ?"),
    Hymn.new("Hymns/Choir-Is-Your-All-On-The-Altar.mp3","Choir - Is Your All On The Altar ?"),
    Hymn.new("Hymns/Choir-It-Is-Well.mp3","Choir - It Is Well With My Soul"),
    Hymn.new("Hymns/Choir-I-Will-Sing-The-Wondrous-Story.mp3","Choir - I Will Sing The Wondrous Story"),
    Hymn.new("Hymns/Choir-Jesus-Is-Calling.mp3","Choir - Jesus Is Calling"),
    Hymn.new("Hymns/Choir-Jesus-Is-Mine.mp3","Choir - Jesus Is Mine"),
    Hymn.new("Hymns/Choir-Jesus-Loves-Even-Me.mp3","Choir - Jesus Loves Even Me"),
    Hymn.new("Hymns/Choir-Just-As-I-Am.mp3","Choir - Just As I Am"),
    Hymn.new("Hymns/Choir-Lead-On-O-King-Eternal.mp3","Choir - Lead On Oh King Eternal"),
    Hymn.new("Hymns/Choir-Let-Jesus-Come-Into-Your-Heart.mp3","Choir - Let Jesus Come Into Your Heart"),
    Hymn.new("Hymns/Choir-Look-To-The-Lamb-Of-God.mp3","Choir - Look To The Lamb Of God"),
    Hymn.new("Hymns/Choir-Look-Ye-Saints.mp3","Choir - Look Ye Saints"),
    Hymn.new("Hymns/Choir-Lord-Im-Coming-Home.mp3","Choir - Lord I'm Coming Home"),
    Hymn.new("Hymns/Choir-Love-Divine.mp3","Choir - Love Divine"),
    Hymn.new("Hymns/Choir-Love-Lifted-Me.mp3","Choir - Love Lifted Me"),
    Hymn.new("Hymns/Choir-Majestic-Sweetness.mp3","Choir - Majestic Sweetness"),
    Hymn.new("Hymns/Choir-Man-Of-Sorrows.mp3","Choir - Man Of Sorrows"),
    Hymn.new("Hymns/Choir-Medly.mp3","Choir - Medley Assorted"),
    Hymn.new("Hymns/Choir-Medly-Choruses.mp3","Choir - Medley Choruses"),
    Hymn.new("Hymns/Choir-Medly-Hear-The-Good-News.mp3","Choir - Medley Hear The Good News"),
    Hymn.new("Hymns/Choir-Medly-Safe-Am-I.mp3","Choir - Medley Safe Am I"),
    Hymn.new("Hymns/Choir-Medly-The-Blood.mp3","Choir - Medley The Blood"),
    Hymn.new("Hymns/Choir-More-Love-To-Thee.mp3","Choir - More Love To Thee"),
    Hymn.new("Hymns/Choir-My-Hope-Is-Built-On-Nothing-Less.mp3","Choir - My Hope Is Built On Nothing Less"),
    Hymn.new("Hymns/Choir-No-Not-One.mp3","Choir - No Not One"),
    Hymn.new("Hymns/Choir-Oh-For-A-Thousand-Tongues.mp3","Choir - Oh For A Thousand Tongues"),
    Hymn.new("Hymns/Choir-Oh-Listen-To-Our-Wondrous-Story.mp3","Choir - Oh Listen To Our Wondrous Story"),
    Hymn.new("Hymns/Choir-Oh-Say-That-Im-Glad.mp3","Choir - Oh Say That I'm Glad"),
    Hymn.new("Hymns/Choir-Oneday.mp3","Choir - One day"),
    Hymn.new("Hymns/Choir-Only-In-Thee.mp3","Choir - Only In Thee"),
    Hymn.new("Hymns/Choir-Out-Of-My-Bondage.mp3","Choir - Out Of My Bondage"),
    Hymn.new("Hymns/Choir-Praise-The-Lord.mp3","Choir - Praise The Lord"),
    Hymn.new("Hymns/Choir-Praise-The-Saviour.mp3","Choir - Praise The Saviour"),
    Hymn.new("Hymns/Choir-Redeemed.mp3","Choir - Redeemed"),
    Hymn.new("Hymns/Choir-Revive-Us-Again.mp3","Choir - Revive Us Again"),
    Hymn.new("Hymns/Choir-Saved-By-The-Blood.mp3","Choir - Saved By The Blood"),
    Hymn.new("Hymns/Choir-Saved-Saved-Saved.mp3","Choir - Saved Saved Saved"),
    Hymn.new("Hymns/Choir-Saviour-Lead-Me-Lest-I-Stray.mp3","Choir - Savoiur Lead Me Lest I Stray"),
    Hymn.new("Hymns/Choir-Shepherd-Of-Love.mp3","Choir - Shepherd Of Love"),
    Hymn.new("Hymns/Choir-Softly-And-Tenderly-Jesus-Is-Calling.mp3","Choir - Softly &amp; Tenderly Jesus Is Calling"),
    Hymn.new("Hymns/Choir-Sunset-Is-Coming-The-Sunrise-We-See.mp3","Choir - Sunset Is Coming The Sunrise We See"),
    Hymn.new("Hymns/Choir-Sweeter-As-The-Years.mp3","Choir - Sweeter As The Years Go By"),
    Hymn.new("Hymns/Choir-Take-Time-To-Be-Holy.mp3","Choir - Take Time To Be Holy"),
    Hymn.new("Hymns/Choir-Tell-Me-The-Old-Old-Story.mp3","Choir - Tell Me The Old Old Story"),
    Hymn.new("Hymns/Choir-That-Man-Of-Calvary.mp3","Choir - That Man Of Calvary"),
    Hymn.new("Hymns/Choir-The-Fight-Is-On.mp3","Choir - The Fight Is On !"),
    Hymn.new("Hymns/Choir-The-Hallelujah-Chorus.mp3","Choir - The Hallelujah Chorus"),
    Hymn.new("Hymns/Choir-Tho-Your-Sins-Be-As-Scarlet.mp3","Choir - Tho Your Sins Be As Scarlet"),
    Hymn.new("Hymns/Choir-Tis-So-Sweet-To-Trust-In-Jesus.mp3","Choir - Tis So Sweet To Trust In Jesus"),
    Hymn.new("Hymns/Choir-Trust-In-The-Lord.mp3","Choir - Trust In The Lord"),
    Hymn.new("Hymns/Choir-Turn-Your-Eyes-Upon-Jesus.mp3","Choir - Turn Your Eyes Upon Jesus"),
    Hymn.new("Hymns/Choir-We-Shall-Shine-As-The-Stars.mp3","Choir - We Shall Shine As The Stars"),
    Hymn.new("Hymns/Choir-What-A-Friend-We-Have-In-Jesus.mp3","Choir - What A Friend We Have In Jesus"),
    Hymn.new("Hymns/Choir-What-Did-He-Do.mp3","Choir - What Did He Do ?"),
    Hymn.new("Hymns/Choir-What-Will-You-Do-With-The-King.mp3","Choir - What Will You Do With The King ?"),
    Hymn.new("Hymns/Choir-When-I-See-The-Blood.mp3","Choir - When I See The Blood"),
    Hymn.new("Hymns/Choir-When-I-Survey.mp3","Choir - When I Survey The Wondrous Cross"),
    Hymn.new("Hymns/Choir-While-Jesus-Whispers.mp3","Choir - While Jesus Whispers"),
    Hymn.new("Hymns/Choir-Why-Do-You-Wait.mp3","Choir - Why Do You Wait ?"),
    Hymn.new("Hymns/Choir-Why-Not-Say-Yes.mp3","Choir - Why Not Say Yes ?"),
    Hymn.new("Hymns/Choir-Wonderful-Name-He-Bears.mp3","Choir - Wonderful Name He Bears"),
    Hymn.new("Hymns/Choir-Wonderful-Words-Of-Life.mp3","Choir - Wonderful Words Of Life"),
    Hymn.new("Hymns/Choir-Yesterday-Today-Forever.mp3","Choir - Yesterday Today Forever"),
    Hymn.new("Hymns/Choir-BeholdYourKing-EasterCantata-1963.mp3","Choir - Behold Your King Cantata (33 minutes)"),
    Hymn.new("Hymns/Duet-Blessed-Redeemer-POP1976.mp3","Duet - Blessed Redeemer"),
    Hymn.new("Hymns/Duet-In-The-Hollow-Of-His-Hand.mp3","Duet - In The Hollow Of His Hand"),
    Hymn.new("Hymns/Duet-Love-Divine.mp3","Duet - Love Divine"),
    Hymn.new("Hymns/MaleChorus-Glorious-Things-Of-Thee-Are-Spoken.mp3","Male Chorus - Glorious Things Of Thee Are Spoken"),
    Hymn.new("Hymns/MaleChorus-Whosoever-Will.mp3","Male Chorus - Whosoever Will"),
    Hymn.new("Hymns/Quartet-Blood-Will-Never-Lose-Its-Power.mp3","Quartet - Blood Will Never Lose It's Power"),
    Hymn.new("Hymns/Quartet-I-Have-Been-Redeemed.mp3","Quartet - I Have Been Redeemed"),
    Hymn.new("Hymns/Quartet-Jesus-Paid-It-All.mp3","Quartet - Jesus Paid It All"),
    Hymn.new("Hymns/Quartet-My-Anchor-Holds.mp3","Quartet - My Anchor Holds"),
    Hymn.new("Hymns/Quartet-Rock-Of-Ages.mp3","Quartet - Rock Of Ages"),
    Hymn.new("Hymns/Quartet-Unveiled-Christ.mp3","Quartet - Unveiled Christ"),
    Hymn.new("Hymns/Solo-D_Stallings-How-Great-Thou-Art.mp3","Solo - D. Stallings-How Great Thou Art"),
    Hymn.new("Hymns/Solo-D_Stallings-I-Know-Whom-I-Have-Believ_ed.mp3","Solo - D. Stallings-I Know Whom I Have Believed"),
    Hymn.new("Hymns/Solo-D_Stallings-I-Surrender-All.mp3","Solo - D. Stallings-I Surrender All"),
    Hymn.new("Hymns/Solo-D_Stallings-Jesus-Is-The-Sweetest-Name.mp3","Solo - D. Stallings-Jesus Is The Sweetest Name I Know"),
    Hymn.new("Hymns/Solo-D_Stallings-Nothing-Between.mp3","Solo - D. Stallings - Nothing Between"),
    Hymn.new("Hymns/Solo-D_Stallings-The-Broken-Heart.mp3","Solo - D. Stallings - The Broken Heart"),
    Hymn.new("Hymns/Solo-D_Stallings-The-Love-Of-God.mp3","Solo - D. Stallings - The Love Of God"),
    Hymn.new("Hymns/Solo-D_Stallings-Yield-Not-To-Temptation.mp3","Solo - D. Stallings - Yield Not To Temptation"),
    Hymn.new("Hymns/Solo-M_Greenhill-I-Want-To-See-My-Saviour.mp3","Solo - M. Greenhill - I Want To See My Savoiur"),
    Hymn.new("Hymns/Solo-M_Greenhill-Jesus-Wept.mp3","Solo - M. Greenhill - Jesus Wept"),
    Hymn.new("Hymns/Solo-M_Greenhill-More-Time-Alone.mp3","Solo - M. Greenhill - More Time Alone"),
    Hymn.new("Hymns/Solo-M_Greenhill-Song-Of-The-Soul-Set-Free.mp3","Solo - M. Greenhill-Song Of The Soul Set Free"),
  Hymn.new("Hymns/Trio-Its-Not-An-Easy-Road.mp3","Trio - It's Not An Easy Road"),
  Hymn.new("Hymns/Trio-Medly-Peace.mp3","Trio - Medley Peace"),
  Hymn.new("Hymns/Trio-Thank-God-For-Jesus.mp3","Trio - Thank God For Jesus"),
  Hymn.new("Hymns/Trio-Turn-Your-Eyes-Upon-Jesus.mp3","Trio - Turn Your Eyes Upon Jesus"),
  Hymn.new("Hymns/Trio-When-He-Calls-Me.mp3","Trio - When He Calls Me"),
  Hymn.new("Hymns/Music-Bristol-Conf-1977.mp3","Bristol Conference Music - 1977"),
  Hymn.new("Hymns/Music-Skyland-Conf-1979.mp3","Skyland Conference Music-1979"),
  Hymn.new("Hymns/Music-Skyland-Conf-1980.mp3","Skyland Conference Music-1980"),
  Hymn.new("Hymns/Music-Skyland-Conf-1981.mp3","Skyland Conference Music-1981"),
  Hymn.new("Hymns/ValleyBibleChapelConcert1981.mp3","Valley Bible Chapel Concert - 1981")
                   ]
  
end
